services:
  - type: web
    name: productsdb-api
    runtime: python
    pythonVersion: "3.11.12"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.12"
